apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        environment: test
        departement: engineering
        tier: backend
      annotations: # Nelson wanted to add this
        kubernetes.io/change-cause : "amigoscode/kubernetes:hello-world-v2" # can have any message that you want 
    spec:
      containers:
      - name: hello-world
        image: amigoscode/kubernetes:hello-world-v2 # we just change the image name (tag)
        resources: # per container
          requests:
            memory: "128Mi" # 128 MB
            cpu: "500m" # 500 millicors // 1 cors is 1000 millicors
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
    name: blue
spec:
  containers:
  - name: blue
    image: amigoscode/kubernetes:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---

apiVersion: v1
kind: Pod
metadata:
  name: green
  labels:
    name: blue
spec:
  containers:
  - name: green
    image: amigoscode/kubernetes:green
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: labels-selectors
spec:
  selector:
    name: blue
    environment: test
  ports:
  - port: 80
    targetPort: 80

---  # pinging namespace testing purpose

apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: green
  labels:
    name: blue
spec:
  containers:
  - name: green
    image: amigoscode/kubernetes:green
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

