apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret
spec:
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      volumes:
        - name: secret-1 # could be anything
          secret:
            secretName: mysecret # must match its secret name
      containers:
      - name: secret
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: AMIGOS_SECRET # could be anything
            valueFrom:
              secretKeyRef:
                name: mysecret-from-file # must match its secret name
                key: tuna # must match its secret property name
        volumeMounts:
          - mountPath: /etc/secrets # could be anywhere else inside the container 
            name: secret-1 # must match volume name
